apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx 
spec:
  selector:
    matchLabels:
      app: myapp #SAME 1. Ties them together
  replicas: 3
  template: #Same Pod definition.
    metadata:
      name: nginx-2
      labels:
        app: myapp #SAME 1. Ties them together
    spec:
      containers:
        - name: nginx
          image: nginx
