#THE DEPLOY FOR REDIS

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:

    #The labels from the Pod's metadata's labels.
    matchLabels:
       name: redis-pod
       app: demo-boting-app

  #The exact same as POD metadata and spec:
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-boting-app 
    
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379