#THE DEPLOY FOR RESULT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:

    #The labels from the Pod's metadata's labels.
    matchLabels:
       name: result-app-pod
       app: demo-boting-app

  #The exact same as POD metadata and spec:
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-boting-app 
    
    spec:
      containers:
        - name: result-app 
          image: kodekloud/examplevotingapp_result:v1 
          ports:
            - containerPort: 80 