#THE RESULT APP SERVICE:

apiVersion: v1
kind: Service

metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-boting-app #The name of the application

spec:
  type: NodePort

#It's a frontend application which runs on the port 80.
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005 #External port
  selector:
  #These values should match the result-pod metadata labels.
     name: result-app-pod
     app: demo-boting-app
