#THE POD

apiVersion: v1
kind: Pod

metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-boting-app #The name of the application

spec:
  containers:
    - name: voting-app #The name of the container
      image: kodekloud/examplevotingapp_vote:v1 #Tag: v1
      ports:
        - containerPort: 80 #The port on which the application listens for this voting app