#THE DEPLOY FOR WORKER

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:

    #The labels from the Pod's metadata's labels.
    matchLabels:
       name: worker-app-pod
       app: demo-boting-app

  #The exact same as POD metadata and spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-boting-app
    
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1
          ports:
            - containerPort: 80